import './globals.css'
import Modal from '@/components/Modal'

export const metadata = {
  title: 'PeeknDo',
  description: 'Generated by Aryan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='sbg-[#F5F6F8]' >{children} 
      <Modal /></body>
    </html>
  )
}
